services:
  discord-keycloak-rolesync:
    image: NotActuallyTerry/discord-keycloak-rolesync
    build:
      context: .
    environment:
      DISCORD_BOT_TOKEN:
      KEYCLOAK_URL:
      KEYCLOAK_USERNAME:
      KEYCLOAK_PASSWORD:
      KEYCLOAK_REALM:
      KEYCLOAK_ADMIN_REALM:
    restart: on-failure